### PR TITLE
Tagging

### LINKED ISSUE #7: Image Tags
#### As a user I want to add tags to images.

__Story__:

Our users are loving the ability to add images to our service. However, now
that there are more than a handful of images, it is apparent that we need some
way to filter images by certain categories. In order to do that, we first need
to label images in some way. It is time to add the ability for our users to tag
images when they add them.

__Acceptance criteria__:
- [x] When I add a new image, there is a form field to add tags.
- [x] After I've saved an image with tags, I see those tags displayed with the
  associated image.
- [x] My application uses the acts-as-taggable-on gem to provide the tagging
  functionality.

__Reference material__:
- https://github.com/mbleigh/acts-as-taggable-on

__Note__: You should allow images to have no tags; this sets the stage for a later issue.

__Dependencies__:
- Image Index

### PR DESCRIPTION
**Pull request by lelandmiller**
Closes #7

### CODE REVIEW

**Comment by lelandmiller** [comment]
[[Ropes] Image tags](https://trello.com/c/JAqgFc86/1083-ropes-image-tags)

**Comment by zldavis** [comment]
Overall looks good 👍 

Do you think it would be valuable to add a test for the controller `show` action that verifies the tags are rendered on that page?

**Comment by lelandmiller** [comment]
@zldavis, sounds good. Would it be reasonable to add it in #26. It would just be easier since I move some of the test helpers around in there.

**Comment by zldavis** [comment]
yeah thats fine

**Pull request merged**
